import Image from "next/image";
import Link from "next/link";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";

const articleTitles = [
  "Apple Unveils Watch Series 12 and Ultra 4", "iPhone 18 Pro vs iPhone 17 Pro: Should You Upgrade?", "iPad vs Drawing Tablet: Which One Is Better for Digital Art?", "The Complete iPad Guide: Setup, Features, Tips, and Troubleshooting", "Best Blood Pressure Monitors for Home Use", "Laptop Buying Guide: Things to Consider When Choosing a Laptop", "Top 5 Best Camera Phones in Bangladesh", "How to Choose the Best Air Conditioner", "Best Mini Fan in Bangladesh", "CCTV vs. WiFi Camera: Which Is Better for Home or Office?", "Best Monitors for Video Editing in Bangladesh", "Best Waterproof Laptop Backpacks", "How to Build a Productive Home Office", "Gaming PC Buying Guide for Beginners", "Best Wireless Headphones for Everyday Use", "How to Keep Your Laptop Running Faster", "Smart Home Devices Worth Considering", "Understanding Laptop RAM and Storage", "Best Keyboards for Work and Gaming", "Technology Trends to Watch This Year",
];
const articleImages = ["https://www.startech.com.bd/image/cache/catalog/blog/2026/apple-unveils-watch-series-12-and-ultra-4/apple-unveils-watch-series-12-and-ultra-4-cover-420x198.webp", "/images/products/monitor.svg", "/images/products/laptop.svg", "/images/products/headphone.svg", "/images/products/keyboard.svg", "/images/products/desktop-pc.svg"];
const articles = articleTitles.map((title, index) => [title, articleImages[index % articleImages.length], index % 3 === 0 ? "Tech Trends" : index % 3 === 1 ? "Buying Guides" : "Comparisons", `${String((index % 27) + 1).padStart(2, "0")} Sep 2026`, `${(index % 9) + 3} min. read`]);
const slugify = (value: string) => value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");

export default async function AuthorPage({ params }: { params: Promise<{ author: string }> }) {
  const { author } = await params;
  const name = author === "nexora-tech-team" ? "Nexora Tech Team" : author.split("-").map((word) => word.charAt(0).toUpperCase() + word.slice(1)).join(" ");
  return <><Header breadcrumbs={[{ label: "Home", href: "/" }, { label: "Blog", href: "/blog" }, { label: name }]} /><main className="blog-page"><div className="blog-page__content"><section className="author-profile"><div className="author-profile__logo">N</div><div><span>Nexora Tech Author</span><h1>{name}</h1><small>Web Content Team</small><p>A team of technology experts and enthusiasts sharing the latest gadgets, guides, comparisons, and tips to help you make smarter technology choices.</p><strong>Connect Expert: <a className="author-profile__facebook" href="https://facebook.com" target="_blank" rel="noopener noreferrer" aria-label="Nexora Tech Team on Facebook"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M24 12.073c0-6.627-5.373-12-12-12s-12 5.373-12 12c0 5.99 4.388 10.954 10.125 11.854v-8.385H7.078v-3.47h3.047V9.43c0-3.007 1.792-4.669 4.533-4.669 1.312 0 2.686.235 2.686.235v2.953H15.83c-1.491 0-1.956.925-1.956 1.874v2.25h3.328l-.532 3.47h-2.796v8.385C19.612 23.027 24 18.062 24 12.073z" /></svg></a></strong></div></section><div className="blog-grid">{articles.map(([title, image, category, date, time], index) => <article className={`blog-card blog-card--${index % 6}`} key={title}><div className="blog-card__image"><Image src={image} alt="" width={160} height={120} /><span>{category}</span></div><div className="blog-card__body"><div className="blog-card__meta"><span>{date}</span><span>{time}</span></div><h3><Link href={`/blog/${slugify(title)}`}>{title}</Link></h3><p>Read helpful technology news, product advice, and practical buying information.</p><Link href={`/blog/${slugify(title)}`}>Read More <span>→</span></Link></div></article>)}</div><nav className="blog-pagination" aria-label="Author article pages"><span>Previous</span><b>1</b><span>2</span><span>3</span><span>Next</span></nav></div></main><Footer /></>;
}
